### ISSUE TITLE
Revise TA Tools task table

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/SCORE#40]
Revise the columns in the TA Tools to include:

1. Name - first name, last name and username in parentheses, e.g. Jane Doe (JaneDoe0101)
2. Step - Step number and name, e.g. 1.1 Getting Started
3. Time Remaining - count down of time left (doesn't need to be implemented yet, let's just have the column blank or "N/A")
4. Requests - Provide options for each respective tasks, e.g. Approve/Reject

**Comment by JoelWiebe** [comment]
Related to issue #39

**Comment by aperritano** [comment]
@JoelWiebe can you review and close this? thanks
