### ISSUE TITLE
Only display student timer in VLE if "Tasks" contain a timer

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/SCORE#81]
Currently when ONLY the "Request Help" and "Request Approval" tasks are specified for a step in the authoring tool, timer information is also displayed in the students' VLE.

Duration: 0
Time Remaining NA:NA

Timer information should only be displayed in the student VLE when the a timer duration is specified.

**Comment by aperritano** [comment]
@JoelWiebe needs review
