### ISSUE TITLE
Send student to next step with "Task" approval 

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/SCORE#83]
Approval of a step in "Tasks" was designed to send the student to the very next step in the project. 

Steps to reproduce:
- In authoring tool, create a step that has an "Approval Request"
- As student, navigate to the step that has an "Approval Request" and click the request button
- In Teacher Tools "Tasks", click the thumbs up icon to approve

The student in the VLE will be advanced 2 steps and get the following error in the browser console:

![image](https://user-images.githubusercontent.com/6416247/93378892-ad66e680-f822-11ea-8d79-77988e21aa02.png)

You may use the following project. Group 1/2/3 - Group Attempt have approval requests.
[44.zip](https://github.com/encorelab/SCORE/files/5234777/44.zip)

**Comment by aperritano** [comment]
@JoelWiebe what build did you get this error on? I downloaded the project and loaded it into my local build — it works fine. 

Can you clarify?

**Comment by JoelWiebe** [comment]
@aperritano Oh, interesting. I'm getting this error on the latest score_develop both locally and on the servers.

**Comment by hirokiterashima** [comment]
Hmm. I see this issue too. It looks like the issue is on the server end. The command to "goToNextNode" is being fired twice, which results in students moving ahead by two steps. I wonder when this change occurred...

I'll take a closer look.
